#!/usr/bin/env bash
# Sheet ownership guard for KiCad feature branches.
#
# A branch feature/<name> may only change the protected files (KiCad sources,
# CI configuration, CI-generated outputs) that .github/sheet-ownership.conf
# assigns to <name>. Other files (docs, CHANGELOG, footprints in *.pretty/,
# 3D models ...) are always allowed.
#
# The mapping is read from BASE_REF, not from the branch under test, so a
# branch cannot grant itself files by editing the mapping.
#
# Environment:
#   FEATURE_BRANCH  e.g. feature/power-gen            (required)
#   BASE_REF        branch to compare against          (default origin/dev)
#   HEAD_REF        commit to check                     (default HEAD)
#   GUARD_MODE      fail | warn                         (default fail)
#   OWNERSHIP_FILE  mapping file on BASE_REF (default .github/sheet-ownership.conf)
#
# Run locally from the repo root:
#   FEATURE_BRANCH=$(git branch --show-current) bash .github/scripts/check_sheet_ownership.sh

set -euo pipefail

FEATURE_BRANCH="${FEATURE_BRANCH:?FEATURE_BRANCH is required, e.g. feature/power-gen}"
BASE_REF="${BASE_REF:-origin/dev}"
HEAD_REF="${HEAD_REF:-HEAD}"
GUARD_MODE="${GUARD_MODE:-fail}"
OWNERSHIP_FILE="${OWNERSHIP_FILE:-.github/sheet-ownership.conf}"
SUMMARY="${GITHUB_STEP_SUMMARY:-/dev/null}"
ON_CI="${GITHUB_ACTIONS:-false}"

# Files that hold shared design state, matched on the file name.
PROTECTED_NAMES=('*.kicad_sch' '*.kicad_pcb' '*.kicad_pro' '*.kicad_dru' '*.kicad_sym' 'sym-lib-table' 'fp-lib-table')
# CI configuration, matched on the path.
CI_CONFIG_PATHS=('.github/*' 'kibot_yaml/*' 'kibot_resources/*')
# Outputs that CI generates and commits on dev (see kibot_yaml/kibot_main.yaml).
# Committing them on a feature branch makes binary merge conflicts with dev.
GENERATED_PATHS=('README.md' 'Schematic/*' 'Manufacturing/*' 'Testing/*' 'Images/*' '3D/*'
                 'Reports/*' 'HTML/*' 'KiCanvas/*' 'KiRI/*')

feature="${FEATURE_BRANCH#feature/}"

trim() { local s="$1"; s="${s#"${s%%[![:space:]]*}"}"; s="${s%"${s##*[![:space:]]}"}"; printf '%s' "$s"; }

# Prints why a file is protected (kicad | ci-config | generated); fails if it is not.
# shellcheck disable=SC2053  # intentional glob matches below
protection() {
  local f="$1" p
  for p in "${GENERATED_PATHS[@]}"; do [[ $f == $p ]] && { echo generated; return 0; }; done
  for p in "${CI_CONFIG_PATHS[@]}"; do [[ $f == $p ]] && { echo ci-config; return 0; }; done
  for p in "${PROTECTED_NAMES[@]}"; do [[ ${f##*/} == $p ]] && { echo kicad; return 0; }; done
  return 1
}

hint() {
  case "$1" in
    generated) echo "is generated by CI on dev. Drop it from your branch: git checkout origin/dev -- '$2' (or git rm '$2' if new)" ;;
    ci-config) echo "is CI configuration. Change it on dev (integrator), not on a feature branch" ;;
    *)         echo "is not owned by $FEATURE_BRANCH. Revert it, or ask the integrator to make this change on dev" ;;
  esac
}

# --- read the mapping from the base branch -----------------------------------
if ! git rev-parse --verify -q "$BASE_REF" >/dev/null; then
  echo "::error::Base ref '$BASE_REF' not found (did checkout use fetch-depth: 0?)"
  exit 1
fi
if ! mapping="$(git show "$BASE_REF:$OWNERSHIP_FILE" 2>/dev/null)"; then
  echo "::error::$OWNERSHIP_FILE not found on $BASE_REF"
  exit 1
fi

allowed=()
while IFS= read -r line || [[ -n "$line" ]]; do
  line="${line%%#*}"
  [[ "$line" == *=* ]] || continue
  name="$(trim "${line%%=*}")"
  pattern="$(trim "${line#*=}")"
  [[ -n "$name" && -n "$pattern" ]] || continue
  [[ "$name" == "$feature" ]] && allowed+=("$pattern")
done <<< "$mapping"

if ((${#allowed[@]} == 0)); then
  msg="Branch '$FEATURE_BRANCH' has no entry in $OWNERSHIP_FILE on $BASE_REF. Add a line '$feature = <sheet file>' on dev before working on this branch."
  echo "::error::$msg"
  { echo "### Sheet ownership guard"; echo; echo "❌ $msg"; } >> "$SUMMARY"
  exit 1
fi

# --- compare against the merge base ------------------------------------------
merge_base="$(git merge-base "$BASE_REF" "$HEAD_REF")"

violations=()
reasons=()
owned=()
while IFS= read -r -d '' f; do
  kind="$(protection "$f")" || continue
  ok=false
  for p in "${allowed[@]}"; do
    # shellcheck disable=SC2053
    [[ $f == $p ]] && ok=true && break
  done
  if $ok; then owned+=("$f"); else violations+=("$f"); reasons+=("$kind"); fi
done < <(git diff --name-only --no-renames -z "$merge_base" "$HEAD_REF")

# --- report -------------------------------------------------------------------
{
  echo "### Sheet ownership guard: \`$FEATURE_BRANCH\`"
  echo
  # shellcheck disable=SC2016  # backticks are markdown, not expansion
  echo "Owned patterns: $(printf '`%s` ' "${allowed[@]}")"
  echo
  for f in "${owned[@]}";      do echo "- ✅ \`$f\`"; done
  for i in "${!violations[@]}"; do echo "- ❌ \`${violations[i]}\` $(hint "${reasons[i]}" "${violations[i]}")"; done
  ((${#owned[@]} + ${#violations[@]})) || echo "_No protected files changed._"
} >> "$SUMMARY"

echo "Branch:  $FEATURE_BRANCH  (feature '$feature')"
echo "Compare: $(git rev-parse --short "$merge_base")..$(git rev-parse --short "$HEAD_REF")  (merge base with $BASE_REF)"
echo "Owned:   ${allowed[*]}"
for f in "${owned[@]}"; do echo "  ok        $f"; done

if ((${#violations[@]} == 0)); then
  echo "Result: OK"
  exit 0
fi

level=error; [[ "$GUARD_MODE" == "warn" ]] && level=warning
for i in "${!violations[@]}"; do
  f="${violations[i]}"
  echo "  NOT OWNED $f  (${reasons[i]})"
  [[ "$ON_CI" == "true" ]] && echo "::$level file=$f,title=Sheet ownership::$f $(hint "${reasons[i]}" "$f")."
done
echo "Result: ${#violations[@]} file(s) outside this branch's ownership"
[[ "$GUARD_MODE" == "warn" ]] && exit 0
exit 1
